export const ActionTypes = {
    SET_RESTAURENTS:"SET_RESTAURENTS",
    SELECTED_RESTAURENT:"SELECTED_RESTAURENT",
    SEARCH_RESTAURENT:"SEARCH_RESTAURENT",
    REMOVE_SELECTED_RESTAURENT:"REMOVE_SELECTED_RESTAURENT",
};